# Generated by Django 4.0 on 2022-01-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdl_articles',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
